### ISSUE TITLE
Stop Loading in wp_footer

### ISSUE THREAD

**Issue by hirenshah** [oceanwp/ocean-modal-window#1]
This causes such an issue with other dependancies, because they would be required on more or less every single page.  This impacts the performance of the entire site and adversely affects the user experience.

Modals should only be included in wp_footer when they are needed rather than all the time.

**Comment by raindrop-digital** [comment]
I agree, we use the modal windows on product pages / some sites we have used only on one page and it loads across the whole website. This needs fixing.

**Comment by eramits** [comment]
Hello,

Sorry for the late response. We were not checking this page regularly but from now we will check it regularly. Regarding this issue, I'll try to fix it in the next update. 

Thank you

**Comment by MarkHollo** [comment]
@mohammadTaghiElmi what do you think of this suggestion?

**Comment by MarkHollo** [comment]
Since this thread was opened there have been significant improvements in loading assets, as well as the full user control over the conditions so we hope you all like those and have had a chance to experience them in full.

If you have any other suggestions of have any of the features could be improved, please feel free to get involved because OceanWP products are for you :)
